language: node_js
node_js:
  - stable
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g istanbul

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
